name: actions

on:
  push:

jobs:
  test-actions:
    name: test-action
    runs-on: ubuntu-latest
    steps:
      - name: list files
        run: ls
      - name: checkout repo
        uses: actions/checkout@v4.1.1
      - name: list files
        run: ls
      - name: Print to Log
        id: print-to-log
        uses: actions/hello-world-javascript-action@main
        with:
          who-to-greet: paul    
      - name: time
        run: echo "greeting time:" ${{ steps.print-to-log.outputs.time }}
        
