name: actions

on:
  push:

jobs:
  test-actions:
    name: test-action
    runs-on: ubuntu-latest
    steps:
      - name: list files
        run: ls
      - name: checkout repo
        uses: actions/checkout@v4.1.1
      - name: list files
        run: ls
    
